DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'BureauRole') THEN
        CREATE TYPE "BureauRole" AS ENUM ('PRESIDENT', 'VICE_PRESIDENT', 'TRESORIER', 'SECRETAIRE', 'MATERIEL');
    END IF;
END $$;

ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bureau" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bureau_role" "BureauRole";
