services:
  web:
    build: .
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: postgresql://theobessel:root@db:5432/grinp
      ORIGIN: https://grinp.inpt.fr
      REDIRECT_URI: https://grinp.inpt.fr/login
      CHURROS_CLIENT_ID: ${CHURROS_CLIENT_ID}
      CHURROS_CLIENT_SECRET: ${CHURROS_CLIENT_SECRET}
      DEV: true
      BODY_SIZE_LIMIT: 10M
    ports:
      - "80:3000"
      - "3000:3000"
    depends_on: [db]
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: theobessel
      POSTGRES_PASSWORD: root
      POSTGRES_DB: grinp
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
